version: "3.8"

services:
  # db:
  #   image: postgres:15
  #   container_name: postgres_db
  #   restart: always
  #   environment:
  #     POSTGRES_DB: mnudb
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: admin
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #     - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  #   ports:
  #     - "5432:5432"

  backend:
    build: ../spring-boot-BE
    platform: linux/arm64
    container_name: spring_backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/mnudb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ../react-FE
    platform: linux/amd64
    container_name: react_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

# volumes:
#   db_data:
